services:
  webapi:
    env_file: ".env"
    image: barzinassa/microidp:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - type: bind
        source: ./aspnetcore.pfx
        target: /https/aspnetcore.pfx
      - type: bind
        source: ./DataProtectionKeys
        target: /app/DataProtectionKeys
    networks:
      - microIDPNetwork
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: microidp
      MONGO_INITDB_ROOT_PASSWORD: microidp
    networks:
      - microIDPNetwork
    volumes:
      - type: bind
        source: ./mongodb
        target: /data/db
networks:
  microIDPNetwork:
