version: "3"
services:
        webapi:
                build: .
                ports:
                   - 5000:80
                networks:
                   - jwtNetwork
                depends_on:
                   - "mongo"
        mongo:
                image: mongo
                networks:
                   - jwtNetwork
                volumes:
                   - type: bind
                     source: ./mongodb
                     target: /data/db
networks:
        jwtNetwork:
